/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Gnosis Research Center",
  "tagline": "\nWe conduct research in High-Performance Computing (HPC) memory and storage systems, especially in the design and prototype development of scalable software systems. \nOur current emphasis is on a scalable system software for data management and data access and on having a better understanding of data-centric systems development.\n",
  "favicon": "img/favicon.ico",
  "url": "https://osama347.github.io",
  "baseUrl": "/spcai/",
  "organizationName": "Spcai PAF-IAST",
  "projectName": "Spcai",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\FAST COMPUTER\\Desktop\\Noman\\spcai\\docusaurus.sidebars.js"
        },
        "blog": {
          "showReadingTime": true
        },
        "theme": {
          "customCss": "C:\\Users\\FAST COMPUTER\\Desktop\\Noman\\spcai\\src\\css\\custom.css"
        },
        "gtag": {
          "trackingID": "G-9SXDPLSLB2"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/social-card.png",
    "metadata": [
      {
        "name": "description",
        "content": "Discover our research center's work in HPC memory and storage systems, emphasizing scalable software, data management, and data-centric system development."
      },
      {
        "name": "keywords",
        "content": "high-performance computing (hpc), memory and storage systems, scalable software systems, data management, data-centric systems, research center, scalable system software, technology research, computational research, innovative technology, scientific research"
      }
    ],
    "navbar": {
      "style": "dark",
      "title": "Gnosis Research Center",
      "logo": {
        "alt": "Gnosis Research Center",
        "src": "img/logo.png"
      },
      "items": [
        {
          "label": "Gnosis",
          "position": "left",
          "items": [
            {
              "to": "/about",
              "label": "About"
            },
            {
              "to": "/members",
              "label": "Members"
            },
            {
              "to": "/network",
              "label": "Network"
            },
            {
              "to": "/contact",
              "label": "Contact"
            }
          ]
        },
        {
          "label": "Research",
          "position": "left",
          "items": [
            {
              "to": "/research/projects",
              "label": "Projects"
            },
            {
              "to": "/research/patents",
              "label": "Patents"
            },
            {
              "to": "/resources/hardware-overview",
              "label": "Hardware Overview"
            }
          ]
        },
        {
          "to": "/publications",
          "label": "Publications",
          "position": "left"
        },
        {
          "type": "docSidebar",
          "label": "Tutorials",
          "sidebarId": "tutorialSidebar",
          "position": "right"
        },
        {
          "label": "GitHub",
          "href": "https://github.com/grc-iit",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "links": [
        {
          "title": "Gnosis Research Center",
          "items": [
            {
              "html": "\n                  <p>\n                    Stuart Building <br />\n                    Room 112i and 010 <br />\n                    10 W. 31st Street <br />\n                    Chicago, Illinois 60616\n                  </p>\n                "
            },
            {
              "html": "\n                  <p>\n                    Email: <a href=\"mailto:grc@iit.edu\" target=\"_blank\" rel=\"noopener noreferrer\">grc@iit.edu</a> <br />\n                    Phone: <a href=\"tel:3125676885\" target=\"_blank\" rel=\"noopener noreferrer\">+1 312 567 6885</a>\n                  </p>\n                "
            }
          ]
        },
        {
          "title": "Featured Projects",
          "items": [
            {
              "label": "ChronoLog",
              "to": "/research/projects/chronolog"
            },
            {
              "label": "Labios",
              "to": "/research/projects/labios"
            },
            {
              "label": "Coeus",
              "to": "/research/projects/coeus"
            },
            {
              "label": "Hermes",
              "to": "/research/projects/hermes"
            }
          ]
        },
        {
          "title": "Tutorials",
          "items": [
            {
              "label": "Linux Introduction",
              "to": "/docs/category/linux-introduction"
            },
            {
              "label": "Installing HPC Software",
              "to": "/docs/category/installing-hpc-software"
            },
            {
              "label": "Important Environment Variables",
              "to": "/docs/category/important-environment-variables"
            },
            {
              "label": "C++ Introduction",
              "to": "/docs/category/c-introduction"
            },
            {
              "to": "/docs/category/ares-research-cluster",
              "label": "Ares User Guide"
            }
          ]
        },
        {
          "title": "Links",
          "items": [
            {
              "label": "GRC GitHub",
              "href": "https://github.com/grc-iit"
            },
            {
              "label": "GRC LinkedIn",
              "href": "https://www.linkedin.com/company/gnosis-research-center/"
            },
            {
              "label": "GRC X",
              "href": "https://twitter.com/grc_iit"
            },
            {
              "label": "GRC YouTube",
              "href": "https://www.youtube.com/channel/UCNtEyAt4_ckpIbX-gSv8sww"
            },
            {
              "label": "Illinois Tech",
              "href": "https://www.iit.edu/"
            },
            {
              "label": "SCS Lab",
              "href": "http://cs.iit.edu/~scs/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 Gnosis Research Center (GRC).",
      "style": "light"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
